### ISSUE TITLE
Permalink to update prebuilt package

### ISSUE THREAD

**Issue by Aqua1ung** [muflone/remmina-plugin-rustdesk#1]
Hello, and tank you for a wonderful piece of software! Would you be able to provide a _permalink_ for those of us who need to download the latest prebuilt package of the Rustdesk plugin please? I need this for scripting purposes, as I am attempting to whip up an update script.

Many thanks again!

**Comment by muflone** [comment]
Hi

I currently build packages for Arch Linux only and the same package is already available in the AUR where you can get it

**Comment by Aqua1ung** [comment]
> I currently build packages for Arch Linux only and the same package is already available in the AUR where you can get it

Thank you! I was wondering why the (prebuilt) plugin does _not_ work for me! You may want to specify the distro in the name of the file from now on, just to avoid confusion. It thus looks like I will have to compile it myself from the source code.

**Comment by muflone** [comment]
Maybe this could help

https://www.muflone.com/remmina-plugin-rustdesk/english/download.html

Is rustdesk included in your distribution repositories? If yes I could build

**Comment by Aqua1ung** [comment]
> Is rustdesk included in your distribution repositories? If yes I could build

Are you by any chance saying that we need to have Rustdesk installed in order to build/compile the Remmina plugin? (I am looking to build the plugin precisely because my distro does _not_ (yet) have a Rustdesk package.)

So is Rustdesk required for the compiling of the plugin?

**Comment by muflone** [comment]
> Are you by any chance saying that we need to have Rustdesk installed in order to build/compile the Remmina plugin? (I am looking to build the plugin precisely because my distro does _not_ (yet) have a Rustdesk package.)
> 
> So is Rustdesk required for the compiling of the plugin?

No no
Rustdesk is needed to use the plugin, not to build it but the dependency must be set in the dependencies list for the deb package, so if rustdesk would be available it would make sense to build it for Debian

Unfortunately seems Debian doesn't ship rustdesk in its repositories

**Comment by Aqua1ung** [comment]
> Unfortunately seems Debian doesn't ship rustdesk in its repositories

My distro is [Clear Linux](https://www.clearlinux.org/). I have been trying to compile the plugin from source, but I get a missing dependency (`gio-unix-2.0`). So far I [do not know how to fix that](https://community.clearlinux.org/t/gio-unix-2-0-not-found/9159).

**Comment by muflone** [comment]
> My distro is [Clear Linux](https://www.clearlinux.org/). I have been trying to compile the plugin from source, but I get a missing dependency (`gio-unix-2.0`). So far I [do not know how to fix that](https://community.clearlinux.org/t/gio-unix-2-0-not-found/9159).

I don't know how Clear Linux works but this library if provided by glib2 2.78

**Comment by Aqua1ung** [comment]
Alright, so I installed [glib 2.78.](https://download.gnome.org/sources/glib/2.78/). Here's what error message I am getting:
```
dad@DadsGram~/Downloads/remmina-plugin-builder-1.4.31.0 $ cmake -DCMAKE_INSTALL_PREFIX=/usr .
CMake Deprecation Warning at CMakeLists.txt:37 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Remmina Plugin Builder, version 1.4.31.0
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info

...

-- Looking for include file errno.h
-- Looking for include file errno.h - found
-- Checking for one of the modules 'gio-2.0'
-- Checking for module 'gio-unix-2.0'
--   Package 'gio-unix-2.0', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  cmake/FindGIO.cmake:37 (pkg_check_modules)
  cmake/FindGTK3.cmake:76 (find_package)
  cmake/FindOptionalPackage.cmake:27 (find_package)
  CMakeLists.txt:271 (find_required_package)


-- Configuring incomplete, errors occurred!
```
