### ISSUE TITLE
Plugin in Clear Linux

### ISSUE THREAD

**Issue by Aqua1ung** [muflone/remmina-plugin-rustdesk#2]
So I finally managed to build the plugin in [Clear Linux](https://www.clearlinux.org/):
```
dad@DadsGram~/Downloads/remmina-plugin-builder-1.4.31.0 $ cmake -DCMAKE_INSTALL_PREFIX=/usr .
CMake Deprecation Warning at CMakeLists.txt:37 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Remmina Plugin Builder, version 1.4.31.0
-- Checking for one of the modules 'atk'
-- Found ATK: /usr/lib64/libatk-1.0.so (found version "2.50.0") 
-- Checking for one of the modules 'gdk-3.0'
-- Checking for module 'harfbuzz'
--   Found harfbuzz, version 8.2.1
-- Checking for one of the modules 'pango'
-- Found Pango: /usr/lib64/libpango-1.0.so (found version "1.51.0") 
-- Found GDK3: /usr/lib64/libgdk-3.so (found version "3.24.38") 
-- Found Pango: /usr/lib64/libpango-1.0.so (found version "1.51.0") 
-- Checking for one of the modules 'cairo'
-- Found Cairo: /usr/lib64/libcairo.so (found version "1.18.0") 
-- Checking for one of the modules 'gdk-pixbuf-2.0'
-- Found GDKPixbuf: /usr/lib64/libgdk_pixbuf-2.0.so (found version "") 
-- Found GTK3: /usr/lib64/libgtk-3.so (found version "3.24.38") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done (1.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/dad/Downloads/remmina-plugin-builder-1.4.31.0
dad@DadsGram~/Downloads/remmina-plugin-builder-1.4.31.0 $ make
[ 50%] Building C object remmina-plugin-to-build/remmina-plugin-rustdesk/CMakeFiles/remmina-plugin-rustdesk.dir/src/remmina_plugin.c.o
[100%] Linking C shared library remmina-plugin-rustdesk.so
[100%] Built target remmina-plugin-rustdesk
```
... only to be greeted with the following errors:
![Screenshot from 2023-09-30 11-59-50](https://github.com/muflone/remmina-plugin-rustdesk/assets/12104779/d5d27bd9-4308-4348-bedf-1bfdae1c420e)
![Screenshot from 2023-09-30 12-00-06](https://github.com/muflone/remmina-plugin-rustdesk/assets/12104779/ad324db8-5caa-46e0-a949-95686330f754)

Any thoughts @muflone? Could this be because the plugin source code is too old?

**Comment by muflone** [comment]
@Aqua1ung the error message is telling you no rustdesk executable is available in your system.
Install rustdesk and make sure it's avaiable in the system path

**Comment by Aqua1ung** [comment]
> @Aqua1ung the error message is telling you no rustdesk executable is available in your system. Install rustdesk and make sure it's avaiable in the system path

Thank you. It appears that my understanding of what the Remmina Rustdesk plugin does was way off. It was my impression that if one has the plugin, one does not _need_ to have a Rustdesk client installed--otherwise, why bother using Remmina, when one could very well use Rustdesk itself! Anyway, now I finally get it. You may want to emphasize in the readme that one needs the Rustdesk client installed prior to using the Remmina plugin.

Also, would you care to specify _explicitly_ where the Remmina Rustdesk plugin expects to find Rustdesk installed? My Rustdesk installation is not exactly run-of-the-mill, so I should at least make sure that I place a symlink in the right spot.

**Comment by muflone** [comment]
> Thank you. It appears that my understanding of what the Remmina Rustdesk plugin does was way off. It was my impression that if one has the plugin, one does not _need_ to have a Rustdesk client installed--otherwise, why bother using Remmina, when one could very well use Rustdesk itself!

There are many reasons, mainly because RustDesk offers a very poor way to collect addressed and the address book is available only on RustDesk Pro but also because Remmina can be used to collect all the addresses you need and the plugins will allow you to use Remmina for everything else, instead of multiple clients.

> Anyway, now I finally get it. You may want to emphasize in the readme that one needs the Rustdesk client installed prior to using the Remmina plugin.
> 
> Also, would you care to specify _explicitly_ where the Remmina Rustdesk plugin expects to find Rustdesk installed? My Rustdesk installation is not exactly run-of-the-mill, so I should at least make sure that I place a symlink in the right spot.

https://www.muflone.com/remmina-plugin-rustdesk/english/

https://github.com/muflone/remmina-plugin-rustdesk/issues/1#issuecomment-1732664147
